services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
     args:
       - SUITECRM_VERSION=8.9.3
    pull_policy: build
    ports:
      - "80:80"
    environment:
      TZ: Europe/Berlin
    depends_on:
      - db
    volumes:
      - app_data:/var/www/html
  db:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: suitecrm
      MYSQL_DATABASE: suitecrm
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_data: